### ISSUE TITLE
Upload recorded file by myself

### ISSUE THREAD

**Issue by pwnz22** [grishkovelli/vue-audio-recorder#10]
Hi there!

Is there a way to upload recorded file by myself calling axios and appending recorded file?

**Comment by grishkovelli** [comment]
No. What is your goal?

**Comment by pwnz22** [comment]
I have a form where i want to have this recorder and some other fields. So after recording audio and filling the fields i want to make an API call and sent all info there...

**Comment by grishkovelli** [comment]
@pwnz22 you can pass an ```after-recording``` or a ```select-record``` callback to get a record

**Comment by wokalove** [comment]
> @pwnz22 you can pass an `after-recording` or a `select-record` callback to get a record

how to exatly pass a callback? What did you mean?
