### ISSUE TITLE
Wavesurfer.js integration

### ISSUE THREAD

**Issue by threeel** [grishkovelli/vue-audio-recorder#11]
Hey thank you for this amazing component really like the design and simplicity of it.
I would like to be able to listen to the audio Context so that i can attach a Wavesurfer.js to get some visiualization of the audio being recorded or selected.
is there any possible way that can be easily done?
thanks.

**Comment by grishkovelli** [comment]
@threeel You can use some callbacks  **select-record** & **after-recording**. All of them are returned a record.

**Comment by threeel** [comment]
@grishkovelli i think the select-record & after-recording would be good to render the audio once it is done. What am trying to do is pick the live audio as it is being recorded and render that.
thank you.
