### ISSUE TITLE
Some doubts

### ISSUE THREAD

**Issue by daopapp** [grishkovelli/vue-audio-recorder#12]
It's that possible to use props to doesn't show the audio player?
How can I clear the record list after successful upload?
Another point, it's possible to get the actual value of the player on a pause-recording event, just like after-recording do? 
Tks

**Comment by grishkovelli** [comment]
> It's that possible to use props to doesn't show the audio player?

No

> How can I clear the record list after successful upload?

The recorder doesn't have a functional for it. Try to reload/re-render the recorder.

> Another point, it's possible to get the actual value of the player on a pause-recording event, just like after-recording do?

No, but why?
