### ISSUE TITLE
Responsive design

### ISSUE THREAD

**Issue by AlicanBalik** [grishkovelli/vue-audio-recorder#13]
Hello,

Is it possible to make the design responsive? 

https://imgur.com/a/jV5htWM

Thanks.

**Comment by grishkovelli** [comment]
I thought about this recently, but I don't have much free time.

**Comment by AlicanBalik** [comment]
Then the best scenario will be overriding style.

**Comment by mysteriousHerb** [comment]
Any plan to reimplement this? i feel this could be quite essential as most of app on phone will be distorted..
