### ISSUE TITLE
Record in Wave Format

### ISSUE THREAD

**Issue by Foxh0und** [grishkovelli/vue-audio-recorder#14]
Hi,

As per the ToDo's in the README, you still need to have Wave conversion. Can you tell me what needs to be done on this, I can try and take a look, it's a feature I need.

Kind Regards,
Fox

**Comment by grishkovelli** [comment]
Hello, I'm going to add Wave conversion in this month, but if you can't wait, you can check [old version](https://github.com/grishkovelli/vue-audio-recorder/tree/2.2.0)

**Comment by gkieninger** [comment]
Do you have any plan, when Wav Conversion will be ready?
Thanks
Günter

**Comment by jleaders** [comment]
Just a heads up, [Recorder.js](https://github.com/mattdiamond/Recorderjs) has an [export wav function ](https://github.com/mattdiamond/Recorderjs/blob/master/examples/example_simple_exportwav.html) that was [extracted to a minimal npm package](https://www.npmjs.com/package/audiobuffer-to-wav) so you don't have to reinvent the wheel here

**Comment by grishkovelli** [comment]
I've added **format** [option](https://github.com/grishkovelli/vue-audio-recorder/commit/94fc582eef902e4b661c6539148b5caa854262bf)

**Comment by ad34** [comment]
sorry to comment on an old & closed issue but for some reason my recordings are still in mp3 even if I add format="wav"

**Comment by ad34** [comment]
ok the version on npm (3.0.1) does not have the format option , is there already a published version with this feature @grishkovelli  ?
