### ISSUE TITLE
When pausing and starting again, the final track is only the last one.

### ISSUE THREAD

**Issue by antoniohof** [grishkovelli/vue-audio-recorder#16]
When pausing the recording and then resuming, the final uploaded track is just the last one.

**Comment by robert-moore** [comment]
I've just installed the npm package, but I am still running into this problem. The jsfiddle provided in the demo also seems to have this issue: https://jsfiddle.net/grishkovelli/rb1anxyj/.

**Comment by portikM** [comment]
Still experiencing this issue today.
