### ISSUE TITLE
Excellent plugin! How run in mobile?

### ISSUE THREAD

**Issue by adrianoresende** [grishkovelli/vue-audio-recorder#2]
Is it possible to work on the mobile?

**Comment by grishkovelli** [comment]
thnx. I'm not sure, I'll check it and add a fix if possible

**Comment by adrianoresende** [comment]
iPhone 8 safari don't work.

**Comment by saveroo** [comment]
with samsung s7 edge chrome also doesnt work

**Comment by saveroo** [comment]
> with samsung s7 edge chrome also doesnt work
> Remote debugger
> `Uncaught TypeError: Cannot read property 'getTracks' of undefined at t.value (vue-audio-recorder.min.js?c115:1) at VueComponent.toggleRecorder (vue-audio-recorder.min.js?c115:1) at click (vue-audio-recorder.min.js?c115:1) at invoker (vue.esm.js?a026:2027) at HTMLDivElement.fn._withTask.fn._withTask (vue.esm.js?a026:1826)`

turns out, it doesnt work on http.... when i deploy to firebase it works as expected

**Comment by grishkovelli** [comment]
It works perfectly on real devices (IOS & Android) by HTTPS.
But if you use a simulator it may not work, you can see exception **OverconstrainedError** `"Invalid constraint" `  as a consequence  `Cannot read property 'getTracks'`

**Comment by liamcharmer** [comment]
Tried on iOS Chrome, no luck

**Comment by cwilby** [comment]
@liamcharmer fucking hell, that's all you did?  "Tried on iOS Chrome"...?
