### ISSUE TITLE
When pausing and starting again, the final track is only the last clip

### ISSUE THREAD

**Issue by robert-moore** [grishkovelli/vue-audio-recorder#21]
I see this was supposed to be addressed in #17 but I've just installed the npm package, but I am still running into this problem. The jsfiddle provided in the demo also seems to have this issue: https://jsfiddle.net/grishkovelli/rb1anxyj/.

I get an error thrown here: https://github.com/grishkovelli/vue-audio-recorder/blob/master/src/lib/recorder.js#L52

![image](https://user-images.githubusercontent.com/4934366/57023689-aecd4a00-6c00-11e9-975d-57ce79f24c5f.png)

**Comment by grishkovelli** [comment]
thnx a lot. [fixed](https://github.com/grishkovelli/vue-audio-recorder/commit/1f8aad013a44deb495585faddcb75cdbafc5e0cf#diff-85c1e7cb263cbc97a7ded739bfac6ac6L71)
