### ISSUE TITLE
Any way to use with custom HTTP client?

### ISSUE THREAD

**Issue by humblecoder** [grishkovelli/vue-audio-recorder#3]
I like to use a custom Axios instance with appropriate `Auth` headers, etc.  It would be nice to use that (via callback, etc) rather than have to provide a url.

**Comment by grishkovelli** [comment]
Do you use different http instances in your application?

**Comment by humblecoder** [comment]
In a manner of speaking, yes.  It's a medium-sized SPA.  I have sort of a faux repository pattern, each of which imports the custom axios instance and uses it as it sees fit.  However, the common aspect of the axios instance is that it is pre-configured to deal with `Auth` headers, etc. so all traffic to my server is handled correctly.

In this case, I'd like to have something like `@should-upload="myCallback(data)"`.  That way I can send the data with my pre-configured `Auth`.  For a first revision though, the ability to provide auth  headers would be sufficient.

Why do you ask?  🤔

**Comment by grishkovelli** [comment]
@humblecoder The recorder uses the $http method of your application. If you have something like this, then recorder will send an record with these headers. I can't image your case, but ok, I will add ability to add custom headers.

```
...
const http = axios.create({
  baseURL: 'http://localhost:3000',
  headers: {
    'Content-Type': 'application/json',
    'Token': 'MyToken'
  }
})
...
Vue.use(VueAxios, http)
```

**Comment by humblecoder** [comment]
Basically I have various repos for each entity type.  So, for example:

```
import auth from '../services/auth'
import eventBus from '../services/eventBus'
import axios from '../services/customAxiosInstance'

export default class Photo{

  async create(photo_data){
    //CREATE PHOTO
  }

  async delete(photo_id){
    //DELETE PHOTO
  }


  async update(photo_data){
    //UPDATE PHOTO
  }
}
```

. . .and then in my SFC components that  require it, I have:

```
import PhotoClass from '../../api/photo.js'
let Photo = new PhotoClass()

...

Photo.update(photo_data)
```

I realize it's SPA and all gets downloaded anyway, but for the sake of coding, I only import what's needed when and where it's needed.  I don't have a "global" `http` object to speak of.

Thanks, I'll give the update a try.

**Comment by grishkovelli** [comment]
@humblecoder I've added **headers** option
