### ISSUE TITLE
Removing recordings before uploading.

### ISSUE THREAD

**Issue by humblecoder** [grishkovelli/vue-audio-recorder#4]
Perhaps I've missed something, but it would be nice to be able to remove a recording in the list before uploading without having to close the dialog and restart.  For example, if I have 3 recordings, and I botch the 4th recording, I don't want to have to start over, or upload all 4 with the bad one, before recording a 5th.  🤔

**Comment by grishkovelli** [comment]
@humblecoder I added removing record https://github.com/grishkovelli/vue-audio-recorder/commit/fc0c9c824abd07781cf82c0fd8dc6ac8313b6c09
