### ISSUE TITLE
Recorded volume is far too low

### ISSUE THREAD

**Issue by sonicviz** [grishkovelli/vue-audio-recorder#46]
Recordings are extremely low volume. 

Is there any way to adjust the gain?

**Comment by jakedewitt87** [comment]
I am also experiencing this issue. I am not seeing a way to control this, any help with this would be appreciated. Thanks!

**Comment by sonicviz** [comment]
Weird thing is on iPad it's ok, but on desktop windows/android I can barely hear it. Mic settings seem the same. 
Not sure what is going on.

**Comment by sonicviz** [comment]
Any clues on this?

**Comment by sonicviz** [comment]
I'd check your mic settings. I've done extensive debugging and even changed the recorder algo to confirm. 
It's likely a hardware issue with something else grabbing the mic.

**Comment by SergejSi** [comment]
Same problem, are there any build in solutions?
