### ISSUE TITLE
Change Key Name

### ISSUE THREAD

**Issue by halilyuce** [grishkovelli/vue-audio-recorder#50]
Hello,

thanks for this amazing plugin.
I want to change the 'audio' key name with a custom one, for example, 'file'.

I could not find any prop for it, is there any possibilities to do it?

**Comment by grishkovelli** [comment]
Is it about this? https://github.com/grishkovelli/vue-audio-recorder/blob/c316c58243b52be8b0cc59198fa589374542b71b/src/components/uploader.vue#L30

**Comment by halilyuce** [comment]
Oh yeap, that's it! Thanks 👍  :)
