### ISSUE TITLE
undefined $on property

### ISSUE THREAD

**Issue by tjdud0123** [grishkovelli/vue-audio-recorder#51]
Hello! The library works well, thanks!
But I got an error message saying,

> Error in mounted hook: "TypeError: Cannot read property '$on' of undefined"

I think the error occurred because this.$eventBus in recorder's mounted hook is undefined.
Do you know how to fix it? Thanks!

**Comment by grishkovelli** [comment]
It should work, because of https://github.com/grishkovelli/vue-audio-recorder/blob/7e89d8a33ad0afdac0005e4317df152baaabe47f/src/index.js#L15
Maybe I'm wrong. Try to add the same code to your app.

**Comment by tjdud0123** [comment]
Oh, I have noticed that I had to add `import Vue from 'vue';` in order to use `Vue.use(AudioRecorder);.`

And I recommend you to update Usage in README.md.
To update, add` import Vue from 'vue';` and explain how to use components in part of inserting components
 
```
components: {
    AudioRecorder: AudioRecorder.AudioRecorder,
    AudioPlayer: AudioRecorder.AudioPlayer,
  },
```
or
the way you think better

Thanks a lot! It works very well!
