### ISSUE TITLE
Audio file size

### ISSUE THREAD

**Issue by jjones3535a** [grishkovelli/vue-audio-recorder#7]
Thanks for creating this package, looks great!

I noticed the file sizes of the recorded audio is quite large.  Is it possible to compress the WAV files on the fly or somehow reduce the recorded file size?

**Comment by grishkovelli** [comment]
I added support mp3 instead of wav.

**Comment by grishkovelli** [comment]
@frandiox Are you sure that Google's API doesn't support mp3?
