### ISSUE TITLE
Upload to server doesn't work

### ISSUE THREAD

**Issue by romansalin** [grishkovelli/vue-audio-recorder#8]
There is an issue with upload, "this.record" doesn't exist in uploader.vue component.

**Comment by romansalin** [comment]
There is an issue with upload, "this.record" doesn't exist in uploader.vue.

**Comment by grishkovelli** [comment]
@romansalin Can you show me more details?

**Comment by romansalin** [comment]
Just try your live demo — it doesn’t work.

**Comment by grishkovelli** [comment]
I should update the demo. Try clone the repo and call ```npm install && npm run dev```

**Comment by ameft** [comment]
Sorry @grishkovelli, but I've the same problem of @romansalin. I tried v2 and v3 on my app and I can't upload to server.
When i click on the save icon and error appears in the console and the request never arrives to the sever.
`Uncaught TypeError: Cannot convert undefined or null to object
    at Function.assign (<anonymous>)
    at VueComponent.upload (vue-audio-recorder.min.js:1)
    at click (vue-audio-recorder.min.js:1)
    at invoker (vue.runtime.esm.js:2023)
    at HTMLDivElement.fn._withTask.fn._withTask (vue.runtime.esm.js:1822)
upload @ vue-audio-recorder.min.js:1
click @ vue-audio-recorder.min.js:1
invoker @ vue.runtime.esm.js:2023
fn._withTask.fn._withTask @ vue.runtime.esm.js:1822`

**Comment by grishkovelli** [comment]
@ameft @romansalin It's [fixed](https://github.com/grishkovelli/vue-audio-recorder/commit/d8d3d1491e0f4d8a0fe1d4c9ba2538b07d16c872) in 3.0.1

**Comment by ameft** [comment]
@grishkovelli actually I still have issues. Now the error is:
`Uncaught TypeError: Cannot read property 'post' of undefined
    at VueComponent.upload (vue-audio-recorder.min.js:1)
    at click (vue-audio-recorder.min.js:1)
    at invoker (vue.runtime.esm.js:2023)
    at HTMLDivElement.fn._withTask.fn._withTask (vue.runtime.esm.js:1822)`
It would be nice to see a working demo.

**Comment by ameft** [comment]
That was it @grishkovelli! I didn't get that part before.. maybe it should be more explocit in the readme.
