### ISSUE TITLE
手机端如何使用

### ISSUE THREAD

**Issue by mypridelife** [grishkovelli/vue-audio-recorder#9]
如题，电脑端可以，用手机访问不行，是否有解决的办法

**Comment by grishkovelli** [comment]
@mypridelife Can you translate it to English?

**Comment by mypridelife** [comment]
computers can, mobile phone not, whether there is a solution

**Comment by grishkovelli** [comment]
@mypridelife look at https://github.com/grishkovelli/vue-audio-recorder/issues/2
